// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdloZTrAODHDRzMq3oxsUFQo6ciSf0d9E',
    appId: '1:487202770935:web:70f24c70f1829d11dde8f2',
    messagingSenderId: '487202770935',
    projectId: 'lolo-app-club',
    authDomain: 'lolo-app-club.firebaseapp.com',
    storageBucket: 'lolo-app-club.appspot.com',
    measurementId: 'G-DEGB0S0GMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBreW1wKmn2lkt9DSqshGGUhoJPRg9WLec',
    appId: '1:487202770935:android:98e9c85a2dc500aadde8f2',
    messagingSenderId: '487202770935',
    projectId: 'lolo-app-club',
    storageBucket: 'lolo-app-club.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAnjx9i27c8o257JG7YYDGncax3D5JDvE',
    appId: '1:487202770935:ios:ad29931cc47635d9dde8f2',
    messagingSenderId: '487202770935',
    projectId: 'lolo-app-club',
    storageBucket: 'lolo-app-club.appspot.com',
    iosBundleId: 'com.loloApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAnjx9i27c8o257JG7YYDGncax3D5JDvE',
    appId: '1:487202770935:ios:c18abbe4315cbccfdde8f2',
    messagingSenderId: '487202770935',
    projectId: 'lolo-app-club',
    storageBucket: 'lolo-app-club.appspot.com',
    iosBundleId: 'com.example.loloApp.RunnerTests',
  );
}
