// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ3OI8xebit4a5JKCBuoV1Pi5tOyFaeLg',
    appId: '1:858756775400:web:5d463c8b2ceeafe1bef85d',
    messagingSenderId: '858756775400',
    projectId: 'lolo-app-38ca7',
    authDomain: 'lolo-app-38ca7.firebaseapp.com',
    storageBucket: 'lolo-app-38ca7.appspot.com',
    measurementId: 'G-BGS4Q75NSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE-2x-UD7a--UYJO8QwwKkFhYa8rUcvcs',
    appId: '1:858756775400:android:cd9cdc3ceda052c7bef85d',
    messagingSenderId: '858756775400',
    projectId: 'lolo-app-38ca7',
    storageBucket: 'lolo-app-38ca7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV23dHAIj4D2Oyxp8Nx1pTirnPSodqKDM',
    appId: '1:858756775400:ios:5c6fd937e15012c8bef85d',
    messagingSenderId: '858756775400',
    projectId: 'lolo-app-38ca7',
    storageBucket: 'lolo-app-38ca7.appspot.com',
    iosBundleId: 'com.loloApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV23dHAIj4D2Oyxp8Nx1pTirnPSodqKDM',
    appId: '1:858756775400:ios:d5ec063230a0da2bbef85d',
    messagingSenderId: '858756775400',
    projectId: 'lolo-app-38ca7',
    storageBucket: 'lolo-app-38ca7.appspot.com',
    iosBundleId: 'com.example.loloApp.RunnerTests',
  );
}
